- build.sh
- rhcos/4.9/Dockerfile
- rhcos/interface.sh
A basic easy extensible structure to publish repos.
More generalization is possible, but the basics are there.
The Dockerfile for rhcos always downloads the latest rhco 4.9 image and
verifies that the published shasum matches the download.
The build script on top, makes use of an interface function
`containerdisks::needs_update` which returns the shasum of the new
to-download image, or returns nothing if no update is necessary.
This function can work since every containerdisk gets labeled with the
shasum of the containerdisk file itself. Skopeo queries the remote image
to get the info.
> Basic RHCOS publishing structure

- build.sh
- fedora/35/Dockerfile
- fedora/interface.sh
Add a Fedora 35 containerdisk to the build process. Like the rhcos image it will detect shasum differences and rebuild in the periodic job if necessary.
```release-note
Add a Fedora 35 containerdisk
```
> Add a Fedora 35 containerdisk

- pkg/build/tar.go
- pkg/build/tar_test.go
CDI detects the disk directory entry as a regular file due to checking
if the tar header points to a directory by checking if it is appended
with a slash instead of checking the tar type.
To make the images works with all all CDI versions as well as meeting
this expectation in general (most apps append a slash), adding a slash
to the directories here too.
An improvment to CDI is here: https://github.com/kubevirt/containerized-data-importer/pull/2050
```release-note
Append a slash to the disk directory tar header to not confuse CDI
```
> Append a slash to tar directory entries

- cmd/medius/publish.go
- pkg/repository/repository.go
Quay seems to remember when tags have existed and returns a special
error which is not handled by generic libraries in this case. To deal
with it, literally compare strings to detect this kind of error.
```release-note
NONE
```
> Deal with a quay.io strangeness when tags get deleted

- .gitignore
- Makefile
- hack/kubevirtci.sh
This adds a script to fetch the latest kubevirtci and the make targets
to run a kubevirtci cluster in usual fashion.
```release-note
None
```
> Add kubevirtci and cluster-[up|down] make targets

- cmd/medius/common/options.go
- cmd/medius/images/common.go
- cmd/medius/images/promote.go
- cmd/medius/images/push.go
- cmd/medius/images/verify.go
- cmd/medius/main.go
- pkg/api/artifact.go
- pkg/repository/repository.go
This adds the cmd 'images promote', which promotes verified
containerdisks from a source to a target registry.
The cmd shares most of its logic with 'images verify', so the shared
parts were moved to common.go.
**Which issue(s) this PR fixes**:
Fixes #2
Merge after #18
```release-note
Add cmd to promote verified containerdisks to another registry
```
> Add images promote cmd

- cmd/medius/common/options.go
- cmd/medius/docs/docs.go
- cmd/medius/images/push.go
- cmd/medius/images/verify.go
- cmd/medius/main.go
This allows to specify a source registry to check if updates are needed
and a target registry to push freshly built containerdisks to.
In general this makes specifying registries less ambiguous.
Merge after #21
```release-note
Allow to specify a source registry to check if new containerdisks need to be built.
Allow to specify a target registry to push freshly built containerdisks to.
```
> Add --[source|target]-registry flags to images push cmd

- cmd/medius/common/options.go
- cmd/medius/images/push.go
- cmd/medius/images/verify.go
With this flag exit code 0 is returned even if a worker fails.
```release-note
Add --no-fail flag to 'images push' and 'images verify'
```
> Add --no-fail flag to images [push|verify]

- hack/kubevirtci.sh
Give CI clusters more time to come up.
Fixes issues like in https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-containerdisks-push-nightly/1518611121794191360.
Fixes #
```release-note
NONE
```
> Increase wait timeout for kubevirtci

- artifacts/ubuntu/ubuntu.go
- artifacts/ubuntu/ubuntu_test.go
Fix a copy-past error when copying from the rhcos atrifact. We don't need the shasum as tag in this case. For rhcos we have a special use-case for these tags.
Fixes #
```release-note
NONE
```
> Don't add shasum tags to ubuntu

- cmd/medius/common/registry.go
Add fedora:36 to the artifacts
The UseForDocs flags are also updated, so the latest supported artifact
of each distribution is used for documentation.
```release-note
Add fedora:36 to the artifacts
```
> Add fedora:36 to the artifacts

- cmd/medius/common/registry.go
The UseForDocs flags are updated, so the latest supported artifact
of each distribution is used for documentation.
```release-note
None
```
> Update UseForDocs flags of artifacts

- cmd/medius/common/registry.go
- cmd/medius/images/common.go
- cmd/medius/images/promote.go
- cmd/medius/images/push.go
- cmd/medius/images/verify.go
This attribute allows to specify if the artifact of the entry should
be additionally tagged with ':latest'.
```release-note
Add UseForLatest attribute to common.Registry entries
```
> Add UseForLatest attribute to common.Registry entries

- artifacts/fedora/fedora.go
- artifacts/fedora/fedora_test.go
These versions do not support UEFI and additionally Fedora 33 does not
come with the qemu-guest-agent installed. Because these versions are EOL
they are filtered out instead of adding workarounds.
```release-note
None
```
> Filter out Fedora versions lower than 35

- hack/kubevirtci.sh
/cc @0xFelix 
This avoids any need to keep KUBEVIRT_PROVIDER etc up to date as older
providers such as 1.23 are removed.
Fixes #
```release-note
NONE
```
> kubevirtci: Use defaults for KUBEVIRT_* env vars

- cmd/medius/images/verify.go
- pkg/tests/common.go
This fixes failing periodic CI runs by:
- increasing the maximum retries to 30, VMs have up to 300 seconds to boot before the test fails
- evaluating the correct field for passing `no-fail` to `medius images verify`
```release-note
None
```
> Fix failing periodic CI runs 

- Makefile
This fixes one warning during linting with rowserrcheck.
**Which issue(s) this PR fixes**:
Fixes one warning observed in #55
```release-note
None
```
> feat(Makefile): Update golangci-lint to v1.52.2

- cmd/medius/common/registry.go
This changes gatherArtifactes to use a pointer the the slice it should update. Without this the dynamically gathered artifacts were lost as the variable poiting to the original slice that was passed in was not updated.
This was introduced accidentally during refactorings.
```release-note
None
```
> fix: Use a reference to the registry in gatherArtifacts

- cmd/medius/docs/docs.go
- cmd/medius/images/common.go
- cmd/medius/images/promote.go
- cmd/medius/images/push.go
- cmd/medius/images/verify.go
- pipeline.sh
This changes medius to return an error if no artifact was processed.
Previously no error was returned which allowed focussing on not present
artifacts.
cirros:5.2 does no longer exist, use cirros:6.1 in `pipeline.sh` instead.
```release-note
None
```
> Return error when focus did not match and update pipeline.sh to use cirros:6.1

- pipeline.sh
By dropping the workers flag the pipeline is able to run in more constrained environments by running just one parallel worker.
```release-note
None
```
> fix(pipeline.sh): Drop --workers flag

- cmd/medius/images/common.go
Log correct error when logging worker error.
This regression was introduced in
84225e0ec09e1e1889b88e53e7f07698e0b26922 when renaming variables.
```release-note
None
```
> fix: Log correct error when logging worker error

- artifacts/centos/centos.go
- artifacts/centos/centos_test.go
- artifacts/centosstream/centos-stream.go
- artifacts/centosstream/centos-stream_test.go
- artifacts/fedora/fedora.go
- artifacts/fedora/fedora_test.go
- artifacts/rhcos/rhcos.go
- artifacts/rhcos/rhcos_test.go
- artifacts/rhcosprerelease/rhcos.go
- artifacts/rhcosprerelease/rhcos_test.go
- artifacts/ubuntu/ubuntu.go
- artifacts/ubuntu/ubuntu_test.go
- cmd/medius/common/registry.go
- cmd/medius/docs/docs.go
- cmd/medius/images/verify.go
- pkg/api/artifact.go
- pkg/docs/data/cloudinit.tpl
- pkg/docs/data/ignition.tpl
This adds the distro default usernames to the respective artifacts so
the examples in the generated docs are correct. Instead of potentially
adding the default user again the docs mention the default username in a
comment now.
Instead of using a random username the username provided in the docs is
used to verify containerdisks with SSH.
Fixes #61 
```release-note
None
```
> fix: Add distro default usernames to artifacts and test them

- hack/kubevirtci.sh
https://github.com/kubevirt/containerized-data-importer/pull/2723
Fixes #
```release-note
NONE
```
> chore: stop using deprecated cdi-insecure-registries configmap

- artifacts/centos/centos.go
- artifacts/centos/centos_test.go
- artifacts/centosstream/centos-stream.go
- artifacts/centosstream/centos-stream_test.go
- artifacts/fedora/fedora.go
- artifacts/fedora/fedora_test.go
- artifacts/ubuntu/ubuntu.go
- artifacts/ubuntu/ubuntu_test.go
- cmd/medius/common/registry.go
- cmd/medius/images/push.go
- pkg/api/artifact.go
- pkg/build/build.go
- pkg/common/common.go
Since ENV variables were chosen as the way forward to decorate containerdisks with appropriate default instancetypes and preferences the labels are dropped from the built containerdisks.
Fixes #
```release-note
Labels are dropped from containerdisks, only env variables are kept to decorate images.
```
> cleanup: Drop labels from containerdisks

- artifacts/centos/centos.go
- artifacts/centos/centos_test.go
- artifacts/centosstream/centos-stream.go
- artifacts/centosstream/centos-stream_test.go
- artifacts/fedora/fedora.go
- artifacts/fedora/fedora_test.go
- artifacts/ubuntu/ubuntu.go
- artifacts/ubuntu/ubuntu_test.go
- cmd/medius/common/registry.go
- cmd/medius/docs/docs.go
- cmd/medius/images/common.go
- cmd/medius/images/promote.go
- cmd/medius/images/push.go
- cmd/medius/images/verify.go
- pkg/api/artifact.go
- pkg/build/build.go
- pkg/repository/repository.go
Push an image index to have multiple image manifests, instead of single image manifest when needed.
Jira-Url: https://issues.redhat.com/browse/CNV-38597
Fixes #80
```release-note
Build and push image index
```
> feat: build and push image index

- cmd/medius/common/registry.go
/cc @0xFelix 
This brings them in-line with the DataImportCrons provided by HCO to SSP that all use the u1.medium default instance type:
```yaml
$ yq .[].metadata hyperconverged-cluster-operator/assets/dataImportCronTemplates/dataImportCronTemplates.yaml annotations:
cdi.kubevirt.io/storage.bind.immediate.requested: "true"
name: centos-stream8-image-cron
labels:
instancetype.kubevirt.io/default-preference: centos.stream8
instancetype.kubevirt.io/default-instancetype: u1.medium
annotations:
cdi.kubevirt.io/storage.bind.immediate.requested: "true"
name: centos-stream9-image-cron
labels:
instancetype.kubevirt.io/default-preference: centos.stream9
instancetype.kubevirt.io/default-instancetype: u1.medium
annotations: …
```
> registry: Bump default instance type env variables

- pkg/build/build.go
OCI runtimes like [crun-vm](https://github.com/containers/crun-vm) may be able to run a containerdisk container image directly, in which case it is unfortunate that user must pass in a placeholder entrypoint to docker-run and equivalents, since engines like Docker require an entrypoint to be set:
```console
$ docker run --runtime crun-vm quay.io/containerdisks/fedora:39 unused-entrypoint
```
Instead, set the entrypoint to a predetermined "no-entrypoint" value that runtimes like crun-vm can interpret as there not being an entrypoint.
**Which issue(s) this PR fixes**:
```release-note
Changed: The entrypoint for all containerdisks is now ["no-entrypoint"]
```
> Set containerdisks' entrypoint to "no-entrypoint"

- artifacts/fedora/fedora.go
- artifacts/fedora/fedora_test.go
- artifacts/fedora/testdata/releases.json
Starting with Fedora 40 a new filename format is used. The Fedora gatherer is updated to be compatible with the old and new filename formats when parsing them to get additional unique tags for a containerdisk.
Because Fedora is now publishing Cloud_Base and Cloud_Base_UKI
subvariants under the Cloud variant of Fedora, a filter for the
Cloud_Base subvariant is added. This avoids creating Fedora
containerdisks with more than a single image per architecture.
Fixes #
```release-note
None
```
> fix(fedora): Fix Fedora version parsing and add filter for subvariants

- .golangci.yml
- Makefile
/cc @0xFelix 
We've seen some slowness with `v1.57.2`  so this change bumps to `v1.59.1` and handles the deprecation/rename of `gomnd` to `mnd`.
Fixes #
```release-note
NONE
```
> golangci-lint: Bump to v1.59.1 and replace gomnd with mnd

- artifacts/opensuse/leap/leap.go
- artifacts/opensuse/leap/leap_test.go
- artifacts/opensuse/tumbleweed/tumbleweed.go
- artifacts/opensuse/tumbleweed/tumbleweed_test.go
- cmd/medius/common/registry.go
/hold
/cc @0xFelix 
With https://github.com/kubevirt/common-instancetypes/pull/193 in place we can now provide default instance types and prefrences for the recently introduced OpenSUSE containerdisks.
Fixes #
```release-note
ENV variables for default instance types and preferences have been added to the `amd64` OpenSUSE Tumbleweed and Leap containerdisks.
```
> opensuse: Add default instance type and preference ENV vars

- hack/kubevirtci.sh
Instead of using the latest kubevirtci image tag which can be unstable from times to time, use the more heavily tested and stable image tag used by the kubevirt/kubevirt repo.
Fixes #
```release-note
None
```
> chore(ci): Use kubevirtci image tag used by kubevirt/kubevirt

- hack/kubevirtci.sh
cluster-up now lives under kubevirtci folder. This has been modified in https://github.com/kubevirt/kubevirt/pull/12872.
Fixes #
```release-note
None
```
> kubevirtci: Fix paths to cluster-up scripts

- artifacts/centosstream/centos-stream.go
Drops the support for CentOS Stream 8 images.
Fixes # https://github.com/kubevirt/containerdisks/issues/152
```release-note
Drops CentOS Stream 8 support.
```
> feat(centos): Remove CentOS Stream 8 support

- pipeline.sh
CentOS Stream supports a wider range of architectures, making this change a logical step toward enhancing multiarch testing.
```release-note
NONE
```
> ci: test the CentOS Stream distribution in pipeline.sh

- pipeline.sh
The kubevirtci provider version 1.31 is the first release that supports the s390x architecture.
```release-note
NONE
```
> ci: set default kubevirtci provider to version 1.31

- artifacts/fedora/fedora.go
In Fedora, Secure Boot must be disabled to successfully run a new s390x VM.
```release-note
NONE
```
> fix: secure boot not enabled on s390x

- artifacts/fedora/fedora.go
- artifacts/fedora/fedora_test.go
The Fedora 40 image is currently unable to boot with qemu-system-s390x. As this issue likely requires a resolution at the image level, we can temporarily prevent the image from being built for this architecture.
```release-note
NONE
```
> fix: disable Fedora 40 for s390x

- Makefile
- go.mod
Bump golang to 1.24.1
Bump golang to 1.24.1
Fixes #
```release-note
None
```
> Bump golang to 1.24.1

- artifacts/centosstream/centos-stream.go
- artifacts/centosstream/centos-stream_test.go
- artifacts/debian/debian.go
- artifacts/debian/debian_test.go
- artifacts/debian/testdata/debian-11-genericcloud-amd64.json
- artifacts/debian/testdata/debian-11-genericcloud-arm64.json
- artifacts/debian/testdata/debian-12-genericcloud-amd64.json
- artifacts/debian/testdata/debian-12-genericcloud-arm64.json
- artifacts/fedora/fedora.go
- artifacts/fedora/fedora_test.go
- artifacts/opensuse/leap/leap.go
- artifacts/opensuse/leap/leap_test.go
- artifacts/opensuse/tumbleweed/tumbleweed.go
- artifacts/opensuse/tumbleweed/tumbleweed_test.go
- artifacts/ubuntu/ubuntu.go
- artifacts/ubuntu/ubuntu_test.go
- cmd/medius/common/registry.go
- cmd/medius/images/push.go
- pkg/api/artifact.go
- pkg/http/http.go
- testutil/mockgetter.go
It adds support for sha512 checksums, which are required by Debian. Debian image repository only provides sha512 checksums. Moreover, it adds support for Debian 11 and 12 containerdisk on x86_64 and aarm64.
Fixes # [CNV-51712](https://issues.redhat.com/browse/CNV-51712)
```release-note
Added support for Debian 11 and 12 containerdisks.
```
> feat(containerdisk): Add support for Debian containerdisk and sha512 checksums

- cmd/medius/common/registry.go
It will it make more convenient for users just to look for `debian:latest` containerdisk if they just want the most recent version of Debian available.
Fixes #
```release-note
None
```
> chore(debian): Apply `latest` tag to Debian 12

- artifacts/debian/debian_test.go
- cmd/medius/common/registry.go
It provides a default preference and instance type for Debian containerdisks.
Fixes #  [CNV-58379](https://issues.redhat.com/browse/CNV-58379)
```release-note
None.
```
> chore(debian): Add `debian` preference and instancetype to Debian containerdisks

- cmd/medius/common/options.go
- cmd/medius/images/verify.go
This feature allows users to override the automatic detection of the architecture based on the node. Additionally, it paves the way for future enhancements, such as the ability to skip certain verifications based on the specified target architecture.
```release-note
NONE
```
> feat: Add target architecture as a parameter for verification.

- README.md
It adds debian containerdisk list and adds some instructions to guide users for pushing and verifying containersdisk against a kubevirtci cluster.
Fixes #
```release-note
None
```
> chore(README): Add debian and improvements

- cmd/medius/docs/docs.go
- pkg/docs/data/description.tpl
- pkg/docs/docs.go
This extends description.tpl with examples, that show how to use or
import containerdisks with virtctl create.
It also introduces the getPreferredArtifact helper, which will try to find
the artifact with the amd64 to allow using it for documentation purposes.
Fixes #
```release-note
None
```
> docs: Add virtctl create examples 

- cmd/medius/common/registry.go
This adds the latest Ubuntu release `25.04` (Plucky Puffin) which will be supported from April 2025 until January 2026.
Version `25.04` is not a LTS release so it could be debated if it necessary to include it. 
However one of the nice benefits of kubevirt compared to containers in Kubernetes is the possibility to [run newer Linux kernels](https://blog.cloudflare.com/leveraging-kubernetes-virtual-machines-with-kubevirt/#our-need-for-virtualization), thus having access to current releases as a trusted published containerdisk is very useful.
At a current point in the time there would be up to 5 Ubuntu versions in standard support, 3 LTS releases and up to 2 current releases: https://ubuntu.com/about/release-cycle or https://endoflife.date/ubuntu
So …
> feat(ubuntu): Add Ubuntu 25.04

- pipeline-periodic.sh
This approach allows for code reuse, enabling testing of different architectures without the need to promote changes.
```release-note
NONE
```
> ci: periodic pipeline can perform a dry run of the promote step
