cmd/medius/common/registry.go

Signed-off-by: David Vossel <davidvossel@gmail.com>

add rhcos 4.10 now that ocp 4.10 has released

---

cmd/medius/images/verify.go
pipeline.sh

Minor tweaks to make the pipeline work with `kubevirtci` clusters and an example based on cirros which can also be used as presubmit entrypoint.
Fixes #
```release-note
NONE
```

Pipeline for testing based on cirros

---

pipeline-periodic.sh

Configuration for the peroidic pipeline run.
Fixes #
```release-note
NONE
```

Pipeline for the periodic job

---

README.md

Fix invalid URL
Fixes #
```release-note
NONE
```

Fix invalid URL

---

pipeline-periodic.sh

If quay oauth tokens are present, publish docs.
Fixes #14 
```release-note
NONE
```

Push containerdisks docs if a quay oauth token is present

---

OWNERS

Adding 0xFelix, who contributed recently multiple times,
and lyarwood is is known to be a conscientious reviewer.
Signed-off-by: Dominik Holler <dholler@redhat.com>
Adding more reviews to spread the work of doing the code reviews.

Adding additional approvers

---

pkg/build/build.go

This sets the Architecture in config files of containerdisk images to 'amd64'.
Previously the Architecture was empty and tools like 'ctr' failed to import containerdisks because of it.
See https://groups.google.com/d/msgid/kubevirt-dev/4534a4f5-178e-46c2-90ee-ef60a216c7ecn%40googlegroups.com
```release-note
Set Architecture of containerdisks to amd64
```

Set Architecture of containerdisks

---

artifacts/rhcos/rhcos.go
artifacts/rhcos/rhcos_test.go
cmd/medius/common/registry.go

The following images are added/updated:
- RHCOS releases: 4.11, 4.12, latest
- RHCOS pre-releases: 4.12, 4.13
- CirrOS: 6.1
```release-note
None
```

chore(registry): Update the registry of containerdisks to build

---

Makefile

This adds the `lint` target as dependency to the `test` target.
```release-note
None
```

feat(Makefile): Run linters before running unit tests

---

pkg/docs/docs.go

This was introduced in b63107a9dce71cbbf83ecef0ca98f67429e569a0 by mistake.
Fixes https://github.com/kubevirt/containerdisks/issues/57
```release-note
None
```

fix(docs): Fix call to cases.Title

---

.golangci.yml
Makefile

Pull in changes from https://github.com/kubevirt/kubevirt/pull/9962
```release-note
None
```

Update golangci-lint and remove unsupported linters

---

artifacts/centos/centos.go
artifacts/centos/centos_test.go
artifacts/centosstream/centos-stream.go
artifacts/centosstream/centos-stream_test.go
artifacts/fedora/fedora.go
artifacts/fedora/fedora_test.go
artifacts/rhcos/rhcos.go
artifacts/rhcos/rhcos_test.go
artifacts/rhcosprerelease/rhcos.go
artifacts/rhcosprerelease/rhcos_test.go
artifacts/ubuntu/ubuntu.go
artifacts/ubuntu/ubuntu_test.go
cmd/medius/common/registry.go
cmd/medius/images/push.go
pipeline-periodic.sh
pkg/api/artifact.go
pkg/build/build.go

Add additional labels to containerdisks which can carry information like an
appropriate instancetype or preference to use with the containerdisk.
Fixes #
Merge after #74 
```release-note
Provide labels with default instancetype and preference in containerdisks
```

feat: Add additional labels to containerdisks

---

OWNERS

Remove 'codingben' from the OWNERS
```release-note
None
```

Remove 'codingben' from the OWNERS

---

pipeline-periodic.sh

Add force rebuild feature to pipeline-periodic.sh, which allows to rebuild all containerdisks regardless of whether they have changed or not. Enable it by setting the env variable FORCE_REBUILD to true.
Fixes #
```release-note
None
```

feat: Add force rebuild feature to pipeline-periodic.sh

---

README.md

To run local testing of Medius,
developer will need to setup
a local container registry.
```release-note
None
```

docs: add setup local registry

---

README.md

Add a list of containerdisks and supported
architectures.
Signed-off-by: Ben Oukhanov <boukhanov@redhat.com>
```release-note
None
```

docs: add supported architectures

---

cmd/medius/common/registry.go

$subject, introduces a containerdisk for the latest LTS version of Ubuntu.
Fixes #
```release-note
Ubuntu 24.04 Noble Numbat containerdisks are now provided by the project.
```

ubuntu: Add 24.04 Noble Numbat

---

go.mod

Bump golang 1.22.9
Fixes #
```release-note
None
```

Bump golang 1.22.9

---

go.mod

Bump golang 1.23.4 version
Fixes #
```release-note
None
```

chore(golang): Bump golang 1.23.4 version

---

.golangci.yml
Makefile
cmd/medius/images/push.go
pkg/hashsum/hashsum.go
pkg/quay/quay.go

Bump golangci-lint to v2.4.0 and fix all new findings.
Fixes #
```release-note
None
```

chore: Bump golangci-lint
